controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


api_login_check:
    path: /auth/login
    methods: POST


api_register:
    path: /register
    controller: App\Controller\RegisterController::register
    methods: POST
    format: application/json