controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
api_login_check:
    path: /auth/login

api_register:
    path: /register
    controller: App\Controller\RegisterController::register
    format: application/json